CREATE DATABASE IF NOT EXISTS maindb;
USE maindb;
CREATE TABLE IF NOT EXISTS connections (
	id INT AUTO_INCREMENT PRIMARY KEY,
	time TIMESTAMP NOT NULL,
	host VARCHAR(255) NOT NULL,
	port VARCHAR(255) NOT NULL);
	